branches:
  only:
   - master
   - release
language: python
python:
- '3.4'
script:
- python3 .dev/sqf_validator.py
notifications:
  slack:
    urls:
      - secure: $webhook
    on_success: change
    on_failure: always
    on_start: never